# This is a basic workflow to help you get started with Actions

name: hyperscan-build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set git to autocrlf          
        run: git config --global core.autocrlf input

      - name: Checkout w/ submodules and autocrlf
        uses: actions/checkout@v3
        with:
          submodules: true

#      - name: Install Cygwin Action
#        uses: cygwin/cygwin-install-action@v2
#        with:
#          platform: x64
#          packages: make gcc-core
      
      # The cygwin.bat will run out of powershell, and then bash commands work
      - name: Setup build using bash in cygwin
        shell: pwsh
        run: |
          date
          pwd
          date
          dir
          7z x -ax ragel-6.10.tar.gz
          date
          dir
          dir ragel-6.10
          dir hyperscan
