# This is a basic workflow to help you get started with Actions

name: hyperscan-build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set git to autocrlf          
        run: git config --global core.autocrlf input

      - name: Checkout w/ submodules and autocrlf
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Cygwin Action
        uses: cygwin/cygwin-install-action@v2
        with:
          platform: x64
          packages: make gcc
      
      - name: Setup build using bash in cygwin
        run: |
          pwd
          bash ls -la
          bash 7z l boost_1_79_0.7z
          bash 7z x ragel-6.10.tar.gz
          bash 7z x -o hyperscan/ pcre-8.45.zip 
          bash 7z x -o hyperscan/ sqlite-amalgamation-3390000.zip
          bash ls -la
          bash cd ragel-6.10
          bash ./configure
          bash make
          bash make install
          bash cd hyperscan
          bash mkdir build
          bash CMake -G 
