# This is a basic workflow to help you get started with Actions

name: hyperscan-build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set git to autocrlf          
        run: git config --global core.autocrlf input

      - name: Checkout w/ submodules and autocrlf
        uses: actions/checkout@v3
#        with:
 #         submodules: true

      # Setup the dependencies for building.
      - name: Setup build using bash in cygwin
        shell: cmd
        run: |
          echo -- pwd working dir --
          pwd
          echo -- env.GITHUB_WORKSPACE --
          echo ${{ env.GITHUB_WORKSPACE }}
          echo -- show dir --
          dir
          echo -- 7 unzip ragel --
          7z x ragel-6.10.tar.gz
          7z x ragel-6.10.tar
          echo -- show dir --
          dir
          echo -- show ragel dir --
          dir ragel-6.10

      - name: Install Cygwin Action
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: make gcc-core
      
      # The cygwin.bat will run out of cmd, and then bash commands work
      # Alternatively, you can set Cygwin's bash as the shell to use:
      - name: Run cygwin bash shell
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          # This is a real bash script!
          cd ${{ env.GITHUB_WORKSPACE }}
          basic() {
              ls -Al
              pwd
          }
          basic
          cd ragel-6.10
          ./configure
          make
          make install
          
