# This is a basic workflow to help you get started with Actions

name: hyperscan-build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set git to autocrlf          
        run: git config --global core.autocrlf input

      - name: Checkout w/ submodules and autocrlf
        uses: actions/checkout@v3
        with:
          submodules: true

      # Setup the dependencies for building.
      - name: Setup build using bash in cygwin
        shell: cmd
        run: |
          echo -- pwd working dir --
          pwd
          echo -- env.GITHUB_WORKSPACE --
          echo %GITHUB_WORKSPACE%
          echo -- show dir --
          dir
          echo -- 7 unzip ragel --
          7z x ragel-6.10.tar.gz
          7z x ragel-6.10.tar
          7z x pcre-8.45.zip 
          echo -- Force rename to pcre-8.41 on move otherwise build will error out
          move pcre-8.45 hyperscan\pcre-8.41
          7z x sqlite-amalgamation-3390000.zip
          move sqlite-amalgamation-3390000 hyperscan\sqlite3
          7z x -ohyperscan/ boost_1_79_0.7z
          echo -- show dir --
          dir
          echo -- show ragel dir --
          dir ragel-6.10
          echo -- show hyperscan dir --
          dir hyperscan

      - name: Install Cygwin Action
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: make gcc-core
      
      # Alternatively, you can set Cygwin's bash as the shell to use:
      - name: Run cygwin bash shell
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          # This is a real bash script!
          echo -- cd GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          mkdir upload_results
          export UPLOAD_RESULTS=$GITHUB_WORKSPACE/upload_results
          export HYPERSCAN_ROOT=$GITHUB_WORKSPACE/hyperscan
          echo -
          echo -- Add PATH:"/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/"
          echo -
          export PATH=$PATH:"/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/"
          echo -- ls directory
          ls -la
          cd $HYPERSCAN_ROOT
          pwd
          ls -la
          #############################################################
          echo -- cd ragel
          cd $GITHUB_WORKSPACE/ragel-6.10
          echo -- ./configure
          ./configure
          echo -- make then install ragel
          make
          make install
          echo -- ls result
          pwd
          ls -la
          #############################################################
          echo ------
          echo    CMake -G "Visual Studio 16 2019" -A Win32 -DBOOST_ROOT=boost_1_79_0 -DCMAKE_BUILD_TYPE=MinSizeRel
          echo    This cmake builds the vcxproj and sln files for MinSizeRel Win32 settings.
          echo ------
          cd $HYPERSCAN_ROOT
          mkdir build_x32
          cd build_x32
          CMake -G "Visual Studio 16 2019" -A Win32 -DBOOST_ROOT=boost_1_79_0 -DCMAKE_BUILD_TYPE=MinSizeRel ../
          #############################################################
          echo ------
          echo    CMake -G "Visual Studio 16 2019" -A x64 -DBOOST_ROOT=./boost_1_79_0/ -DCMAKE_BUILD_TYPE=MinSizeRel
          echo    This cmake builds the vcxproj and sln files for MinSizeRel x64 settings.
          echo ------
          cd $HYPERSCAN_ROOT
          mkdir build_x64
          cd build_x64
          CMake -G "Visual Studio 16 2019" -A x64 -DBOOST_ROOT=boost_1_79_0 -DCMAKE_BUILD_TYPE=MinSizeRel ../
          #############################################################
          echo -
          echo     msbuild the ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=Win32 _CL_=/MTd
          echo     msbuild the debug x86/Win32 with /MTd MinSizeRel
          echo -
          export _CL_=/MTd
          cd $HYPERSCAN_ROOT/build_x32
          MSBuild.exe ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=Win32
          echo -- Output results
          mkdir $UPLOAD_RESULTS/x32_MTd
          mv lib/* $UPLOAD_RESULTS/x32_MTd
          mv bin/* $UPLOAD_RESULTS/x32_MTd
          echo $UPLOAD_RESULTS/x32_MTd
          ls -la $UPLOAD_RESULTS/x32_MTd
          #############################################################
          echo ------
          echo     msbuild the ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=Win32 _CL_=/MT
          echo     msbuild the nondebug x86/Win32 with /MT MinSizeRel
          echo ------
          export _CL_=/MT
          cd $HYPERSCAN_ROOT/build_x32
          MSBuild.exe ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=Win32
          echo -- Output results
          mkdir $UPLOAD_RESULTS/x32_MT
          mv lib/* $UPLOAD_RESULTS/x32_MT
          mv bin/* $UPLOAD_RESULTS/x32_MT
          echo $UPLOAD_RESULTS/x32_MT
          ls -la $UPLOAD_RESULTS/x32_MT
          #############################################################
          echo ------
          echo     msbuild the ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=x64
          echo     msbuild the debug x64 with /MTd MinSizRel
          echo ------
          export _CL_=/MTd
          cd $HYPERSCAN_ROOT/build_x64
          MSBuild.exe ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=x64
          echo -- Output results
          mkdir $UPLOAD_RESULTS/x64_MTd
          mv lib/* $UPLOAD_RESULTS/x64_MTd
          mv bin/* $UPLOAD_RESULTS/x64_MTd
          echo $UPLOAD_RESULTS/x64_MTd
          ls -la $UPLOAD_RESULTS/x64_MTd
          #############################################################
          echo ------
          echo     msbuild the ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=x64
          echo     msbuild the nondebug x64 with /MT MinSizeRel
          echo ------
          export _CL_=/MT
          cd $HYPERSCAN_ROOT/build_x64
          MSBuild.exe ALL_BUILD.vcxproj -t:Rebuild -p:Configuration=MinSizeRel -p:Platform=x64
          echo -- Output results
          mkdir $UPLOAD_RESULTS/x64_MT
          mv lib/* $UPLOAD_RESULTS/x64_MT
          mv bin/* $UPLOAD_RESULTS/x64_MT
          echo $UPLOAD_RESULTS/x64_MT
          ls -la $UPLOAD_RESULTS/x64_MT
          #############################################################
          echo -
          echo -- Final Results
          echo -
          cd $UPLOAD_RESULTS
          ls -la x*
          
# Now we can upload the output_libs artifacts as the final build.
# Versioning?
          
      - name: Upload output_libs 
        uses: actions/upload-artifact@v3.1.0
        with:
          name: hyperscan_v5.4.0
          path: $UPLOAD_RESULTS
        
 
