# This is a basic workflow to help you get started with Actions

name: test-paths

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Install Cygwin Action
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: make gcc-core
      
      # Alternatively, you can set Cygwin's bash as the shell to use:
      - name: Run cygwin bash shell
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          # This is a real bash script!
          echo -- cd GITHUB_WORKSPACE
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          echo -- ls directory
          ls -la
          echo -- msbuild the ALL_BUILD.vcxproj
          ls "/cygdrive/c/"
          echo -- x86
          ls "/cygdrive/c/Program Files (x86)/"
          echo -- Microsoft Visual Studio
          ls "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/"cd C
          echo -- 2019
          ls "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/"
          echo -- Enterprise
          ls "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/"
          echo -- MSBuild
          ls "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/"
          echo -- MSBuild
          ls "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/"
          echo -- MSBuild
          ls "/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/"
          echo -- Set PATH
          export PATH=$PATH:"/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/"
          printenv
          
